### ISSUE TITLE
Error related to latest regexp_parser release

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#101]
Not sure yet if it requires a refactor on our part or a bugfix in the gem. Relevant info here: https://github.com/ammar/regexp_parser/issues/80

**Comment by rubys** [comment]
reopening as adding the require causes a web pack error; so updating the Gemfile to lock the regexp_parser version version for now.

**Comment by rubys** [comment]
regexp_parser made a fix and that fix has been deployed.
