### ISSUE TITLE
getting started error

### ISSUE THREAD

**Issue by dsisnero** [ruby2js/ruby2js#102]
I tried the getting started with stimulus -starter
$ git clone https://github.com/ruby2js/stimulus-starter.git
$ cd stimulus-starter
$ bundle install
$ yarn install
$ yarn start

f:\programming\source\repos\git\stimulus-starter>yarn start
yarn run v1.22.5
$ snowpack dev
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module 'resolve'
Require stack:
- f:\programming\source\repos\git\stimulus-starter\node_modules\snowpack\lib\index.js
- f:\programming\source\repos\git\stimulus-starter\node_modules\snowpack\index.bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)

**Comment by rubys** [comment]
Not sure why we just now need resolve, but... added!

To try again, start from the top, as in remove the directory and get a fresh clone.
