### ISSUE TITLE
Cache data present in this package releases

### ISSUE THREAD

**Issue by mensfeld** [ruby2js/ruby2js#105]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for Ruby libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that the cache directory is being included.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

Please look into the last two releases. They are over 20MB big while the previous were around 82KB.

The files I'm talking about are present in this directory in the gem releases: `lib/tasks/testrails/tmp/cache/` - I think that the whole `testrails` code is not needed in the gem release.

If the presence of cached data is valid I would love the reasoning. Thanks!

**Comment by rubys** [comment]
Good catch!  Thanks!
