### ISSUE TITLE
Improve documentation around loader integrations

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#107]
~~I'm afraid I've been tardy in my testing of the latest changes to the Webpack loader so I started to take a look today and it appears somehow the effort to support a `rb2js.config.rb` file as an alternative to supplying options directly in the Webpack config file never made it into the codebase. If that's the case, all the documentation on the website is out of date.~~

See [comment below](https://github.com/ruby2js/ruby2js/issues/107#issuecomment-821839169)

**Comment by jaredcwhite** [comment]
Never mind, I think the Opal code in "demo" actually is what becomes the NPM package to do the conversion and that's where the support is so I'm going to test that out now. 😄

**Comment by jaredcwhite** [comment]
Ran into #108, so I'll switch back to v0.1 for now.

**Comment by rubys** [comment]
My thoughts on documentation: `/docs/webpack` and `/docs/snowpack` should be retired in favor of `/docs/integrations`.  Users of webpack with Rails should quickly find their way to `/examples/rails/`, and users of webpack outside of Rails should find what they need at https://www.npmjs.com/package/@ruby2js/webpack-loader

**Comment by jaredcwhite** [comment]
I like your idea on the documentation update.

**Comment by jaredcwhite** [comment]
Added for v5 release.
