### ISSUE TITLE
Error: $.$[](...).$is_a? is not a function

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#108]
Tried upgrading from v1.2 to v2.0 of the Webpack loader which uses the Opal-based parser instead of CRuby, and getting a bunch of Webpack errors, all the same issue:

```
Module build failed (from ./node_modules/@ruby2js/webpack-loader/dist/cjs.js):
webpacker | Error: $.$[](...).$is_a? is not a function
webpacker |     at Object.loader (/Users/jared/apps/PRESETGALAXY/presetgalaxy/node_modules/@ruby2js/webpack-loader/dist/index.js:34:19)
```

**Comment by rubys** [comment]
I'm not seeing this, which is another way of saying I need more information in order to reproduce the problem.

In other news, the strategy of "load rb2js.config.rb when the process begins and never check it again" is making it a bit more difficult to create an automated CI test.  I continue to look into this.

**Comment by jaredcwhite** [comment]
OK I'll try to get a repo spun up that has the problem—if I can!—and let you know…

**Comment by rubys** [comment]
If I had to guess, the problem isn't that the webpack loader doesn't support rb2js.config.rb at all, but that there is something in your rb2js.config.rb that isn't supported.

I'd added a test case.  You can try changing [rb2js.config.rb](https://github.com/ruby2js/ruby2js/blob/3809e676b3903ce3d24a222a9d408d5e1f404c0a/packages/ruby2js/test/ruby2js.js#L58) to see if you can get it to break.

**Comment by jaredcwhite** [comment]
I tried out a brand new project with v2.0.2 of the loader and the rb2js.config.rb example in the docs, and it works fine. So I'll have to circle back around on the problem case I had to figure out what's unique to that. For now, closing this. :+1:

**Comment by jaredcwhite** [comment]
Argh, I ran into this issue again — it's when `autoimports` is included in the config. Various issues around Opal not properly converting the nested object to its proper Hash object, and even with that resolved the keys aren't converted into proper symbol arrays either. Bummer I didn't actually upgrade the main Ruby2JS-related project I've been working on the past few months to v2.0.2 of the loader, or I'd have caught this much sooner.

**Comment by jaredcwhite** [comment]
This is fixed now in https://github.com/ruby2js/ruby2js/commit/91404221aa93683a48486ac2a62f4c3acd387988.
