### ISSUE TITLE
Live playground isn't properly rendering multi-line commnents

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#121]
Not sure what's going on with the Opal context, but it's leaking the `=end` through to the JS instead of rendering `*/`

<img width="240" alt="image" src="https://user-images.githubusercontent.com/658496/120043959-bc14b880-bfc1-11eb-87c5-89caa1e44d2c.png">

**Comment by rubys** [comment]
I presume that was the output, what was the input?

**Comment by jaredcwhite** [comment]
```ruby
=begin
oops
=end
i = 1
```
