### ISSUE TITLE
Loader integration support for esbuild

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#140]
For a recent project, I got Ruby2JS working directly via [esbuild](https://esbuild.github.io/) in a similar fashion to the existing Snowpack, etc. loaders, so I just need to package that up and document it on the website.

**Comment by rubys** [comment]
Cool!  It didn't occur to me to check to see if esbuild had a plugin API.

**Comment by jaredcwhite** [comment]
Yeah, I was confused for a while because Snowpack and Vice use esbuild under the hood but they each have their own plugin APIs. If you use esbuild directly, you can make use of its plugin API. Never a dull moment in the world of frontend bundlers!

**Comment by rubys** [comment]
Might be useful for rails7.  I recently converted the Stimulus Sprockets example to Stimulus Rollup, but Stimulus ESBuild might be even better.

I've started to upgrade the LitElement example to Lit v2 (work in progress, currently broken).  That would also be a good candicate.

**Comment by jaredcwhite** [comment]
Hmm…it appears that Rails 7's new esbuild integration uses a simple CLI one-liner to execute esbuild, which precludes the ability to configure additional plugins. I'd have to play around with it a bit to see if there's an easy way to add a config for specifying plugins.

**Comment by rubys** [comment]
Looks like all it would require is a small mod to `package.json`: https://github.com/rails/jsbundling-rails/blob/c3c4610c35b339dc703afbf29baa2485f5668941/lib/install/esbuild/install.rb; something that could easily be addressed by an install task https://github.com/ruby2js/ruby2js/tree/master/lib/tasks/install

**Comment by jaredcwhite** [comment]
😲 Oooo: https://github.com/excid3/esbuild-rails

**Comment by jaredcwhite** [comment]
Got the loader pretty much down now, been testing out the package in a couple of apps. Just need to write up some documentation, particularly how to get it working with the new jsbundling-rails stuff. Ran into a bit of a blocker for a bit with source map generation, but now that's working great as well. 👍

**Comment by jaredcwhite** [comment]
Regarding docs, I think this needs to happen in conjunction with #107. Right now everything's a bit disjointed. We should probably have a generic JS Bundlers page with preamble, then link to specific package docs or even just the readmes.

**Comment by jaredcwhite** [comment]
Forgot to close this out as part of the v5 release.
