### ISSUE TITLE
[Documentation] Could you add a ~shortish article explaining the key differences to opal?

### ISSUE THREAD

**Issue by rubyFeedback** [ruby2js/ruby2js#144]
Hello there,

I recently found ruby2js. I have not yet tried it; I had problems getting opal to work. I will
give ruby2js a try soon. But I was wondering what key differences may exist. Surely 
there will be trade-offs between the two approaches.

Would it be possible to add a new document and/or at the wiki, and a link to it?
(A new .md file may be easier to handle; github issues is good but the github 
wiki is only meh, in my opinion. Either way having an explanation is a win-win,
so if you may have some time in the future and feel like improving the documentation,
a short comparison would be helpful, just for people to get an overview.)

**Comment by rubys** [comment]
[Super short](https://www.ruby2js.com/docs/choose-your-tool).

[Possibly more helpful](https://www.ruby2js.com/docs/conversion-details).

For the moment, you can run the command line tool as follows:

```
git clone https://github.com/ruby2js/ruby2js.git
ruby ruby2js/demo/ruby2js.rb --help
```

A [change has been committed](https://github.com/ruby2js/ruby2js/commit/cc39ce46f6210532021f8c72416891b6edda69a1) which makes this command available via a `bin` directory, and that will be included in the next release, which is likely within a week or two.
