### ISSUE TITLE
Wrong convertion of .strip function

### ISSUE THREAD

**Issue by lobiklukas** [ruby2js/ruby2js#158]
`.strip` should be converted to `.trim()` function.

```ruby
item = " hello "
item.strip
```

Correct output:
```javascript
let item = " hello ";
item.trim()
```
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/45765609/167409203-395a954d-b5b9-43e7-9fa6-d2295a8e5c37.png">

**Comment by jaredcwhite** [comment]
@lobiklukas That will happen if you enable the `functions`filter. A lot of other useful conversions will be available as well, check out the docs for more info: https://www.ruby2js.com/docs/filters/functions
