### ISSUE TITLE
Dead links and unmaintained appearence 

### ISSUE THREAD

**Issue by ShalokShalom** [ruby2js/ruby2js#176]
The website looks dead, mostly due to missing news since more than one year. 
Secondly, this link (and probably many more too) is dead: 

![Screenshot_56](https://user-images.githubusercontent.com/6344099/185801205-a408a9f6-867b-4a67-a3ac-04d3c42f0a64.png)

https://www.ruby2js.com/examples/

You can prevent this with both local and hosted services: 
https://duckduckgo.com/?t=ffab&q=dead+link+checker&ia=web

P.S: Just had it running and there are like dozens of dead links: 
https://www.deadlinkchecker.com/website-dead-link-checker.asp

![Screenshot_57](https://user-images.githubusercontent.com/6344099/185801441-ac154dde-6e2c-40c5-a9cf-9d745715b06e.png)

**Comment by jaredcwhite** [comment]
Thanks @ShalokShalom for the feedback. The project definitely isn't dead, but there was a bit of a lull earlier this year as our principal long-time maintainer took a step back.

I've started planning out some of the future steps I'd like to take to ensure the long-term health of Ruby2JS going forward, and a refresh of the website is definitely on the list. Appreciate your nudge in this direction and any additional PRs to help use prune or fix links.

**Comment by ShalokShalom** [comment]
One thing I asked myself, is the difference to Opal. 

You might want to add a comparison as well. :)

**Comment by jaredcwhite** [comment]
The website's been updated now with the release of Ruby2JS 5.1 and we're continuing to make updates now and deprecate a bunch of stuff, so this should be much improved soon. Closing for the time being.
