### ISSUE TITLE
404 - some broken links

### ISSUE THREAD

**Issue by yshmarov** [ruby2js/ruby2js#181]
It looks like there are a few broken links on https://www.ruby2js.com/examples/:
<img width="1053" alt="Screenshot 2022-08-29 at 13 48 23" src="https://user-images.githubusercontent.com/13472945/187194438-4a04f819-3017-4246-b7ab-6fed6bd34b21.png">

**Comment by jaredcwhite** [comment]
Thanks @yshmarov, we're tracking this in #176 and #163.
