### ISSUE TITLE
Haml broken -> haml fixed 

### ISSUE THREAD

**Issue by rubydesign** [ruby2js/ruby2js#193]
Hi,
like i said i am starting to code again with ruby2js, and found the haml filter got outdated. Even test failing.

So i dug a little and the haml architecture has changed a bit (as i guess ruby2js), but i got it updated. And the tests fixed.

I am not sure if i am allowed to push, git gave me the ssh option.
Anyway, i wanted to ask before doing that,. The only two affected files are the 

- ruby2js/haml
- spec/haml_spec

Since they were broken i hope it's not a problem

**Comment by rubydesign** [comment]
@jaredcwhite I pushed to a branch now, haml_fix .For you to have a look and also just to see if i really have push rights.

https://github.com/ruby2js/ruby2js/compare/haml_fix

It really is only those two files I can create a pr for it if you think that would be good.

I just made a new wiki page to describe my workflow, and it does rely on this.

Thanks for continuing the work.

**Comment by jaredcwhite** [comment]
@rubydesign I don't much experience with Haml, but this seems like an improvement so LGTM! #198
