### ISSUE TITLE
3.6.0 crashes with:

### ISSUE THREAD

**Issue by sebbASF** [ruby2js/ruby2js#86]
#<SecurityError: Insecure operation, eval without binding option>
      /var/lib/gems/2.7.0/gems/ruby2js-3.6.0/lib/ruby2js/converter/xstr.rb:13:in `block in <class:Converter>'

**Comment by sebbASF** [comment]
3.5.3 is OK

**Comment by rubys** [comment]
Any chance for more reproduction instructions and/or stack traceback?

More background: prior to Ruby 2.7, it was possible to set $SAFE and rely on taintness checks to safely do evals.  Evals were done if the code being converted used back tics.  With Ruby 2.7, these checks became unsafe, so one needs to "opt in" using by passing a binding option.

**Comment by rubys** [comment]
I'm not seeing this with whimsy agenda, roster, or secretary workbench.

**Comment by rubys** [comment]
Found the problem with roster/committers; will follow up on dev@whimsical.

**Comment by rubys** [comment]
Thread: https://lists.apache.org/thread.html/r493797df4e2d734b54c226d3b0927ab19cff71be9737644916dd0063%40%3Cdev.whimsical.apache.org%3E
