### ISSUE TITLE
build a demo powered by Opal

### ISSUE THREAD

**Issue by rubys** [ruby2js/ruby2js#88]
While ruby2js is written in Ruby and getting it to the point where it could convert itself to JavaScript is likely possible, it has a significant dependency on an external gem: [whitequark/parser](https://github.com/whitequark/parser), and converting that is likely to be both difficult and not guaranteed to be successful.

Opal, however, has already done this with [opal-parser](https://github.com/opal/opal/blob/master/docs/opal_parser.md#parsing-ruby-from-javascript-with-opal-parser).  I took a quick look at whether it could handle converting ruby2js, and immediately hit a problem which I opened as https://github.com/opal/opal/issues/2147.

In this case, the problematic code seems to be https://github.com/ruby2js/ruby2js/blob/d80ba963f5be5977f417f09455afa6dc1bae35f2/lib/ruby2js/converter/begin.rb#L35-L37

If a quick fix isn't forthcoming from Opal, it is likely that code can be reworked using [upto](https://ruby-doc.org/core-2.7.0/Integer.html#method-i-upto).  I just don't know yet whether that is the first problem of many or the only issue, or someplace in between.

The end result could be a site like [Opal's Try site](https://opalrb.com/try/?example=Click%20counter#).  This would require a build step (probably in a github action?) which could produce a bundled javascript including all of the filters as well as the relevant [@ruby2js](https://www.npmjs.com/search?q=%40ruby2js) npm modules.

**Comment by jaredcwhite** [comment]
That's a really intriguing idea! I don't think I have a particular need in my typical workflow for a "JS-based" Ruby2JS￼, but it sounds like a way cool tech demo!￼ (and useful in sharing online examples and experimenting)￼

**Comment by rubys** [comment]
It looks like Opal made a fix over a year ago, but has not made progress towards releasing it.

Good news: this appears to be the only change needed to enable opal to compile the core of ruby2js, minus filters and demo.  For the demo, opal does not have support for optparse nor cgi.

There is a lot to explore to see what works and what does not work.  As an example, all filters will need to be included, so the current approach of having the `require` of the filter add it to the default filters will not be viable.  The binding option won't work.  Anything that depends on Proc#source_location won't work.  Etc.

On the plus side, I haven't done any performance comparisons, but it appears that the javascript loads faster than equivalent Ruby so it may reduce things like webpack build times.

**Comment by rubys** [comment]
Progress:

```
$ opal -I lib -r ruby2js -r corelib/string/unpack -e "puts Ruby2JS.convert('x = 1')"
Failed to load WithCLexer, using pure Ruby lexer
var x = 1
```

Not sure what is going on with the need to require unpack; I see no such uses within ruby2js itself.  But without it, I get:

```
$ opal -I lib -r ruby2js -e "puts Ruby2JS.convert('x = 1')"
Failed to load WithCLexer, using pure Ruby lexer

/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:85188
        } else { throw $err; }
                 ^
constructor [RuntimeError]: To use String#unpack, you must first require 'corelib/string/unpack'.
    at String.$raise (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:4646:50)
    at String.$unpack (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:8487:19)
    at constructor.$source_buffer= (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:29387:36)
    at Opal.send (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:1671:19)
    at /tmp/opal-nodejs-runner-20210110-314391-18zsgsv:41120:9
    at constructor.$parse (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:41126:14)
    at /tmp/opal-nodejs-runner-20210110-314391-18zsgsv:41138:22
    at constructor.$parse_with_comments (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:41141:14)
    at Function.$parse (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:85171:21)
    at Function.$convert (/tmp/opal-nodejs-runner-20210110-314391-18zsgsv:85013:19)
```

**Comment by rubys** [comment]
@jaredcwhite I've got this mostly working, and will need help figuring out how to deploy it.

To see it working:

``
cd ruby2js/demo
bundle install
rake
```

Start the docs server, and visit http://localhost:4001/demo/?ruby=a.last&filter=functions

Try going to the functions dropdown and toggling the filter function.

**Comment by jaredcwhite** [comment]
Cool, I look forward to trying this out over the weekend￼!

**Comment by jaredcwhite** [comment]
This is so awesome! I could imagine another addition where it executes the JS in an iframe after generation so you could truly have a sort of CodePen type environment.

One thing I noticed is the JS file generated by Opal is _massive_…like around 20MB. I don't think it's the end of the world because this is by no means a production website for end users, but I wonder if there's any way to whittle that down via minification or some other configuration.

**Comment by rubys** [comment]
Running terser gets it down to 4M (note: I dropped source maps in doing this).  Zipping the result gets it down to 0.75M.  Not being familiar with the bridgetown processing flow, I'm not sure how best to integrate this.

**Comment by jaredcwhite** [comment]
Is it just a rake task? probably can just add it inline as part of the `yarn deploy` script in `package.json`.

**Comment by rubys** [comment]
Seems to work.  Thanks!

**Comment by jaredcwhite** [comment]
That's so cool. No convert button?! It just happens live!

**Comment by rubys** [comment]
Final transfer size for the js: 603.23Kb.
