### ISSUE TITLE
Add method_defined? to functions filter

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#89]
I'm hoping to tackle this soon, so consider this is my todo item. :)

I had to find a JS solution for determining if a method was defined in a class directly (i.e., not in a superclass). That can be done via the `hasOwnProperty` method. I looked for an idiomatic Ruby way to get that information, and it's available via `method_defined?` and a second argument of false (since Ruby 2.6):

https://rubyapi.org/2.6/o/module#method-i-method_defined-3F

To support `method_defined?` with a second argument of true (or no second argument), the JS can use the `"method" in obj` syntax.

**Comment by rubys** [comment]
Cool.  You probably already know this, but just in case, the `"method" in obj` can be produced using `s(:in?, ...)`.  See; https://github.com/ruby2js/ruby2js/blob/master/lib/ruby2js/converter/in.rb
