### ISSUE TITLE
Add Snowpack plugin (similar purpose to Webpack plugin)

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#91]
Snowpack 3.0 just released and it's pretty exciting how it pushes frontend dev forward: https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0

I'd like to implement a plugin for Snowpack, similar to the Webpack one. I'm not sure if that means writing a plugin in JS or Go (?), so I'll write a followup here once I do a little more research.

**Comment by rubys** [comment]
published: https://www.npmjs.com/package/@ruby2js/snowpack-plugin
