### ISSUE TITLE
Add examples to the website

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#93]
The website currently just has "coming soon!" on the Examples page, so I'm planning to start adding some code examples and maybe links to REPLit and so forth. Anyone else have interesting examples of Ruby2JS used in the wild?

**Comment by rubys** [comment]
All of the Apache examples are open source, but the live instances require authentication to access them.  One, however exposes the generated JavaScript without authentication.

Top source file: https://github.com/apache/whimsy/blob/master/www/board/agenda/views/app.js.rb
Require lib: https://github.com/apache/whimsy/tree/master/www/board/agenda/views
Generated output: https://whimsy.apache.org/board/agenda/app.js

**Comment by rubys** [comment]
@jaredcwhite I'd like some help with Bridgetown.  A rough idea of what I would like to accomplish is to host a ruby2js-ified version of https://stimulus.hotwire.dev/handbook/introduction at https://ruby2js.com/examples/stimulus/, complete with navigation within this part of the website.  I'm sure I could figure it out, but I figured you would know off-hand and by asking before I am ready I could save myself some time.  If you could put some blank pages there, I could fill in the content and add more pages when I'm ready.

A preview: go to https://www.ruby2js.com/demo/?filter=esm%2Cstimulus&autoexports=default&es2022, and enter the following Ruby code:

```ruby
class HelloController < Stimulus::Controller
  def greet()
     outputTarget.textContent = "Hello, #{nameTarget.value}!"
  end
end
```

Compare the result to the JS in the top right of https://stimulus.hotwire.dev/

The way I figure it, a substantial portion of the userbase for Stimulus likes the function and footprint of Stimulus, but also is bought into the [Rails Doctrine](https://rubyonrails.org/doctrine/),

Does writing `import` and `export` statements bring you programmer happiness?  How about prefixing references to instance variables with `this.`?

Even in this small example, isn't defining `static targets =` a way of defining configuration?  Why can't it be inferred based on naming conventions?

My plans are to create a ruby2js version of https://github.com/hotwired/stimulus-starter.git, but using snowpack if for no other reason than it provides an excellent ability for the user to "view source" of the individual JavaScript modules produced.

**Comment by rubys** [comment]
Roughed in a [first page](https://github.com/ruby2js/ruby2js/commit/c5018e77fa6e9c03bd3c264413605f433c982b14)... [see it live](https://www.ruby2js.com/examples/stimulus/).  If there is a better way to do things, please fix! :-)

**Comment by jaredcwhite** [comment]
That looks like a good start! I like the idea of the Examples section looking like the other docs with the navigation sidebar. I'll try to dig in shortly with any follow-up tweaks… Also it'd be cool if the demo link could populate the code box automatically without needing to copy/paste

**Comment by rubys** [comment]
There now is a first draft of this content on the website, and the demo link will populate the code box automatically now.  As the code this set of examples depends on is not currently released, you will need to checkout the latest and set your `RUBYLIB` environment variable to include the `lib` directory in your checkout to make this work.

I have a few things I want to clean up before making a release.  If it stretches on, I will make push out a beta.

The next release should be a major release.  A stimulus filter, while significant on its own, is not the biggest change.  A few highlights:

  * The `require` filter will now generate `import` statements when used in combination with the `esm` filter.  You say require and it knows what symbols to import.
  *  Classes and modules are now `open`  and can be extended.
  * Including of modules didn't previously work with attribute accessors (a.k.a. getter and setters)
  * Inheritance now works properly in determining when to automatically add `this.` before method and accessor references within a class
  * References within a class to a method accessed as a property will now automatically bind.  Things like `element.addEventListener :click, self.handle_click.bind(self)` are no longer necessary.

**Comment by jaredcwhite** [comment]
Excited about the 4.0 release and the new Stimulus goodies! Still have to try that out.

In the meantime, I updated the website with a couple of main Example pages and hooked that up with all the Stimulus example pages, so I think that's looking pretty good now. Obviously a lot more we can do to provide helpful samples/tutorials, but can probably close this general issue out for now.
