### ISSUE TITLE
Gotcha regarding Ruby `call` vs JS `call`

### ISSUE THREAD

**Issue by jaredcwhite** [ruby2js/ruby2js#97]
When calling a proc/lambda in Ruby syntax via either `my_lambda.call(123)` or `my_lambda.(123)`, it translates to `my_lambda.call(123)` in the output JavaScript.

The problem there is the call method in JS takes an initial argument that sets the "this" context, so it would really need to be `my_lambda.call(this, 123)` in the output.

I'm not sure what the best solution is. We could default to adding `this` as a first argument in the JS, but then it removes the ability to use Ruby syntax to set the this context using call. On the other hand, Ruby doesn't have a mechanism quite like that…only thing I can think of that's somewhat analogous is `instance_exec`.

Any thoughts?

**Comment by rubys** [comment]
The most natural mapping of `my_lambda.call(123)` in JS would be `my_lambda(123)`.  For my uses to date, I've simply omitted the `.call`.  (Note: the Ruby parser will map `my_lambda.(123)` to `my_lambda.call(123)`).

The functions filter will currently do this for instance variables and class instance variables (`@` and `@@`) but not other variables.  In those cases, `@x(foo)` is not legal Ruby syntax.

Ignoring those two cases for the moment (they can be grandfathered in), I see two general approaches:

1) The current approach, which favors the JavaScript interpretation of `.call`.

2) An `isomorphic` approach, favoring the Ruby interpretation.  For those cases where the JavaScript interpretation is wanted, there always is `.call!`.

This could be handled via the include/exclude capability, much the same way as you are currently including class.

Handling the grandfathering will be slightly messy, but ignoring that: do you have a strong preference for which should be the default?  If we go with the first approach (the current behavior), an `include: [:call]` would get the second behavior.  If we go with the second approach (not backwards compatible, but I don't think it breaks Whimsy), an `exclude: [:call]` would get the first behavior.

**Comment by rubys** [comment]
For now, I went with the first approach as it is backwards compatible.  Feel free to reopen if you disagree.

**Comment by jaredcwhite** [comment]
Thanks, seems like a good approach to me.
